### ISSUE TITLE
Explain how to use and viewing improvs

### ISSUE THREAD

**Issue by martinapugliese** [martinapugliese/tales-science-data#151]
- [x] how to get equation numbering via the extension https://stackoverflow.com/questions/41241984/equation-numbering-in-jupyter-notebooks
 - [x] make code not show up?
- [x] Have to explain that the way things are exposed is inevitably not on the mathematical side of things, for which there's way better material: explain the angle by which this is an interesting book
